name: bpp_riverpod
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^1.0.0
  flutter_screenutil: ^5.0.0
  flutter_svg: ^1.0.0
  freezed_annotation:
  json_annotation: ^4.3.0
  flutter_rating_bar: ^4.0.0
  retrofit: ^2.1.0
  dio: ^4.0.3
  intl: ^0.17.0
  infinite_scroll_pagination: ^3.1.0
  url_launcher: ^6.0.12
  flutter_kakao_login: ^3.4.0
  flutter_staggered_grid_view: ^0.4.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
  retrofit_generator:
  hive_generator: ^1.1.1

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500

    - family: Noto_Sans
      fonts:
        - asset: fonts/Noto_Sans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Noto_Sans/NotoSans-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  fullscreen: true
  android_gravity: center
