name: bpp_riverpod
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 1.0.0-dev.11
  flutter_screenutil:
  flutter_svg: ^0.23.0+1
  freezed_annotation:
  json_annotation: ^4.3.0
  video_player:
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_rating_bar: ^4.0.0
  get_it:
  retrofit:
  dio:
  shared_preferences: ^2.0.8
  jwt_decoder: ^2.0.1
  intl: ^0.17.0
  infinite_scroll_pagination: ^3.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
  retrofit_generator:

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/video/

  fonts:
    - family: Noto_Sans_KR
      fonts:
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 700
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
          weight: 400

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
